apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: kube-system

resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - service-account.yaml
  - service.yaml
  - statefulset.yaml
  - prometheus-alerts-configmap.yaml
  - prometheus-config-configmap.yaml
  - prometheus-records-configmap.yaml