apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: kube-system
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: prometheus-server
    app.kubernetes.io/version: v2.35.0
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/port:   '9090'
spec:
  selector:
    app.kubernetes.io/name: prometheus-server
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30000
      name: prometheus