apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: kube-system
#设置统一的annotations
commonAnnotations:
  prometheus.io/scrape: 'false'
  prometheus.io/port: '3000'
#设置统一的annotations
commonLabels:
  app.kubernetes.io/name: grafana-server
  app.kubernetes.io/version: 8.5.0
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml