---
apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'false'
    prometheus.io/port:   '3000'
  labels:
    app.kubernetes.io/name: grafana-server
    app.kubernetes.io/version: 8.5.0
spec:
  type: NodePort      #这里代表是NodePort类型的
  ports:
    - port: 80          #这里的端口和clusterIP(10.97.114.36)对应，即10.97.114.36:80,供内部访问。
      targetPort: 3000  #端口一定要和container暴露出来的端口对应，nodejs暴露出来的端口是8081，所以这里也应是8081
      protocol: TCP
      nodePort: 30001   # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: grafana           #这里选择器一定要选择容器的标签，之前写name:kube-node是错的。