apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-provisioner
  labels:
    app.kubernetes.io/name: nfs-provisioner
    app.kubernetes.io/version: v4.0.1
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"